---
- name: Install Docker CE on Ubuntu
  hosts: laptop
  become: true
  vars:
    docker_repo: 'deb [arch=amd64] http://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    docker_apt_file: docker-ce
  tasks:
  - name: Docker repo signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Install docker-ce repo
    apt_repository:
      repo: '{{ docker_repo }}'
      filename: '{{ docker_apt_file }}'
      state: present

- name: Install docker-ce
  hosts: laptop
  gather_facts: false
  become: true
  vars:
    # Add packages to the list below
    my_packages:
      names:
        - docker-ce=5:18.09.0*
  tasks:
  - name: Install Docker-CE packages
    apt: name={{ my_packages.names | default([]) }} state=present update_cache=yes

- name: Add user to docker group
  hosts: laptop
  become: true
  tasks:
  - name: User {{ ansible_env.SUDO_USER }} to group docker
    user: append=yes groups=docker name={{ ansible_env.SUDO_USER }}
