---
- name: bashrc setup
  hosts: laptop
  become: false
  tasks:
  # bashrc modifications
  - name: Bash aliases
    blockinfile:
      marker: '# {mark} GIT PROMPT SETUP'
      dest: ~/.bashrc
      content: |
        if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
          . /usr/share/git-core/contrib/completion/git-prompt.sh
          PS1='[\u@\h \W$(__git_ps1 ":(%s)")]$ '
        elif [ -f /usr/lib/git-core/git-sh-prompt ]; then
          . /usr/lib/git-core/git-sh-prompt
          PS1='[\u@\h \W$(__git_ps1 ":(%s)")]$ '
        fi
